### ISSUE TITLE
findNextRec() and findPrevRec()

### ISSUE THREAD

**Issue by ScottDiRoma** [brijsavla/CS435#1]
https://github.com/brijsavla/CS435/blob/4b67b1afbdff610ab43d0ac6cd3a5cfa5eebb9b6/BSTRec.py#L55-L83

Lines 68 and 70 should be a mirror image of lines 81 and 83. As it is right now, findPrevRec() isn't actually a recursive function.

**Comment by brijsavla** [comment]
Made the fix, thank you!
